version: "3"
services:
  portainer:
    image: "portainer/portainer-ce:latest"
    container_name: "portainer"
    command: --admin-password "$$2y$$05$$arC5e4UbRPxfR68jaFnAAe1aL7C1U03pqfyQh49/9lB9lqFxLfBqS"
    ports:
      - "8000:8000"
      - "9000:9000"
    restart: "always"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
