version: "3"
services:
  portainer:
    image: "portainer/portainer"
    container_name: "portainer2"
    ports:
      - "8000:8000"
      - "9000:9000"
    restart: "always"
    volumes:
      - "portainer_data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  portainer_data: